### ISSUE TITLE
Texts in "previous blog post" and "next blog post" links overflow and overlap

### ISSUE THREAD

**Issue by yanghanlin** [harlan-zw/harlanzw.com#11]
### Describe the bug

At the bottom of blog posts on this site, there are links (buttons) pointing to the previous post and the next post. Unfortunately, it seems unable to handle edge cases in which the titles of related posts are so long that the texts overflow and overlap. For example, at the bottom of [this post](https://harlanzw.com/blog/nuxt3-hydration-node-mismatch):

![image](https://user-images.githubusercontent.com/8692892/217132090-e1f5d4d0-79e1-4a15-97c6-a124fd29e00b.png)

### System Info

```Shell
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @YangHanlin 

Thanks for the issue :) This is a Docus issue so I'll wait until they fix it upstream

**Comment by harlan-zw** [comment]
![image](https://user-images.githubusercontent.com/5326365/218369394-9c9a45cb-4108-4e4c-82f3-be5d7accd385.png)

Not perfect but have fixed this for now. Thanks again for making an issue
