### ISSUE TITLE
Projects links are 'undefined'

### ISSUE THREAD

**Issue by devzom** [harlan-zw/harlanzw.com#8]
### Describe the bug
16.12.2022
Generated projects links on production: [https://harlanzw.com/projects](https://harlanzw.com/projects) are generated as `undefined`

### System Info

```Shell
---------
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Oops, thanks for flagging it! Have pushed up a fix

**Comment by devzom** [comment]
@harlan-zw happy to help! thanks for the great work in "Vue" community :)
